/**
 * mockData[HRStaff].ts
 * Data Awal Produksi & Template Default untuk Sistem HR Staff — Divisi Produksi I (PT Batu Karang)
 * Developed by Lalu Mahendra
 */

import { CalonKaryawanItem, LemburItem, LinkArsipItem, MutasiItem, PresensiItem, StaffMember } from './types[HRStaff]';

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 1,
    nama: 'Lalu Mahendra Ali Akbar',
    status: 'TETAP',
    jabatan: 'Koordinator Sistem & Admin Produksi',
    level: 'Staff Senior / Spv',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507122108950001',
    kk: '3507122108950002',
    npwp: '84.921.321.4-652.000',
    email: 'appspengolahan@gmail.com',
    bank: 'BCA',
    rekening: '4390192831',
    telp: '081234567890',
    domisili: 'Malang',
    gajiPokok: 5200000,
    tunjangan: 1250000,
    statusPTKP: 'K/1 (Kawin + 1 Tanggungan)',
    bpjsKesehatanNominal: 150000,
    proyeksiJabatan: 'Asisten Manajer Produksi',
    sanksi: '-',
    limitPKWT: 'Tidak berlaku (TETAP)',
    plafonLevel: 'Grade 4 - Executive Operational',
    deskripsiJabatan: 'Bertanggung jawab atas arsitektur data, rekapitulasi presensi & payroll divisi.',
    faskes: 'Klinik Pratama Rawat Inap Sumber Sehat',
  },
  {
    id: 2,
    nama: 'Andhik Dharmabakti',
    status: 'PKWT 2',
    jabatan: 'Mandor Lapangan Produksi',
    level: 'Staff Madya',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507121504930002',
    kk: '3507121504930003',
    npwp: '75.123.456.7-652.000',
    email: 'andhik.dharmabakti@batukarang.id',
    bank: 'Mandiri',
    rekening: '1440019283741',
    telp: '081398765432',
    domisili: 'Kepanjen, Malang',
    gajiPokok: 3650000,
    tunjangan: 800000,
    statusPTKP: 'K/0 (Kawin, 0 Tanggungan)',
    bpjsKesehatanNominal: 100000,
    proyeksiJabatan: 'Koordinator Mandor',
    sanksi: '-',
    awalPKWT: '2025-10-01',
    akhirPKWT: '2026-10-15', // Sisa hari < 26 hari -> Alert PKWT!
    limitPKWT: 'Kontrak PKWT ke-2',
    plafonLevel: 'Grade 3 - Field Supervisor',
    deskripsiJabatan: 'Pengawasan langsung jalur proses penataan bahan baku dan mesin crusher.',
    faskes: 'Puskesmas Kepanjen',
  },
  {
    id: 3,
    nama: 'M. Solikin',
    status: 'TETAP',
    jabatan: 'Operator Senior Batching Plant',
    level: 'Staff Pelaksana',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507120908880003',
    email: 'm.solikin@batukarang.id',
    domisili: 'Pakisaji, Malang',
    gajiPokok: 4100000,
    tunjangan: 650000,
    statusPTKP: 'K/2 (Kawin + 2 Tanggungan)',
    bpjsKesehatanNominal: 150000,
    proyeksiJabatan: 'Teknisi Utama Mesin',
    sanksi: '-',
    limitPKWT: 'Tidak berlaku (TETAP)',
    plafonLevel: 'Grade 3 - Technical Lead',
    deskripsiJabatan: 'Pengoperasian sistem otomasi PLC dan kalibrasi takaran timbangan.',
    faskes: 'Puskesmas Pakisaji',
  },
  {
    id: 4,
    nama: 'Sugeng Priyanto',
    status: 'PKWT 1',
    jabatan: 'Staff Quality Control Lab',
    level: 'Staff Pratama',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507121203980004',
    email: 'sugeng.p@batukarang.id',
    domisili: 'Bululawang, Malang',
    gajiPokok: 3500000,
    tunjangan: 500000,
    statusPTKP: 'TK/0',
    bpjsKesehatanNominal: 100000,
    proyeksiJabatan: 'Analis Mutu Produk',
    sanksi: '-',
    awalPKWT: '2025-11-01',
    akhirPKWT: '2026-10-18', // Sisa hari < 26 hari -> Alert PKWT!
    limitPKWT: 'Kontrak PKWT ke-1',
    plafonLevel: 'Grade 2 - Specialist Tech',
    deskripsiJabatan: 'Pengujian slump test, kuat tekan beton, dan uji kadar air agregat.',
    faskes: 'Klinik Surya Bululawang',
  },
  {
    id: 5,
    nama: 'Rini Indah Lestari',
    status: 'TETAP',
    jabatan: 'Staff Administrasi & Keuangan Divisi',
    level: 'Staff Madya',
    sekup: 'Administrasi',
    statusAktif: 'Aktif',
    jk: 'Perempuan',
    nik: '3507124507940005',
    email: 'rini.indah@batukarang.id',
    domisili: 'Sukun, Malang',
    gajiPokok: 3900000,
    tunjangan: 750000,
    statusPTKP: 'TK/1 (Lajang + 1 Tanggungan)',
    bpjsKesehatanNominal: 100000,
    proyeksiJabatan: 'Kepala Tata Usaha Divisi I',
    sanksi: '-',
    limitPKWT: 'Tidak berlaku (TETAP)',
    plafonLevel: 'Grade 3 - Financial & Admin',
    deskripsiJabatan: 'Pencatatan kas kecil, verifikasi surat jalan vendor, dan arsip dokumen pabrik.',
    faskes: 'Klinik Husada Sukun',
  },
  {
    id: 6,
    nama: 'Bambang Triwahyudi',
    status: 'TETAP',
    jabatan: 'Mekanik & Pemeliharaan Listrik',
    level: 'Staff Madya',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507121701910006',
    email: 'bambang.tri@batukarang.id',
    domisili: 'Wagir, Malang',
    gajiPokok: 3850000,
    tunjangan: 700000,
    statusPTKP: 'K/2 (Kawin + 2 Tanggungan)',
    bpjsKesehatanNominal: 150000,
    proyeksiJabatan: 'Kepala Workshop Mekanik',
    sanksi: '-',
    limitPKWT: 'Tidak berlaku (TETAP)',
    plafonLevel: 'Grade 3 - Mechanical Spec',
    deskripsiJabatan: 'Maintenance motor conveyor, genset 500kVA, dan panel distribusi daya.',
    faskes: 'Puskesmas Wagir',
  },
  {
    id: 7,
    nama: 'Ahmad Fauzi Ridwan',
    status: 'PKWT 3',
    jabatan: 'Logistik & Penimbangan Bahan Baku',
    level: 'Staff Pratama',
    sekup: 'Administrasi',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507122802960007',
    email: 'fauzi.ridwan@batukarang.id',
    domisili: 'Kepanjen, Malang',
    gajiPokok: 3500000,
    tunjangan: 450000,
    statusPTKP: 'TK/0',
    bpjsKesehatanNominal: 100000,
    proyeksiJabatan: 'Supervisor Gudang & Timbangan',
    sanksi: '-',
    awalPKWT: '2026-01-01',
    akhirPKWT: '2026-12-31',
    limitPKWT: 'Kontrak PKWT ke-3',
    plafonLevel: 'Grade 2 - Logistics Support',
    deskripsiJabatan: 'Input jembatan timbang material masuk (pasir, split, semen) dan stok harian.',
    faskes: 'Puskesmas Kepanjen',
  },
  {
    id: 8,
    nama: 'Dedi Kurniawan',
    status: 'TETAP',
    jabatan: 'Operator Loader & Forklift',
    level: 'Staff Pelaksana',
    sekup: 'Operasional',
    statusAktif: 'Aktif',
    jk: 'Laki-laki',
    nik: '3507120509890008',
    email: 'dedi.k@batukarang.id',
    domisili: 'Gondanglegi, Malang',
    gajiPokok: 3700000,
    tunjangan: 550000,
    statusPTKP: 'K/3 (Kawin + 3 Tanggungan)',
    bpjsKesehatanNominal: 150000,
    proyeksiJabatan: 'Instruktur Alat Berat Divisi',
    sanksi: '-',
    limitPKWT: 'Tidak berlaku (TETAP)',
    plafonLevel: 'Grade 2 - Heavy Equipment',
    deskripsiJabatan: 'Mobilisasi material agregat curah ke hopper feeding dan penataan gudang.',
    faskes: 'Puskesmas Gondanglegi',
  },
];

export const INITIAL_PRESENSI: PresensiItem[] = [];

export const INITIAL_LEMBUR: LemburItem[] = [];

export const INITIAL_CALON: CalonKaryawanItem[] = [];

export const INITIAL_MUTASI: MutasiItem[] = [];

export const INITIAL_LINKS: LinkArsipItem[] = [];

